config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#home"

  resources :services, only: [:index, :show, :new, :create, :destroy] do
    member do
      get 'toggle_favorite', to: "services#toggle_favorite"
    end
    resources :bookings, except: [:destroy, :index, :edit, :update]
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]
  resources :bookings, only: [:destroy, :index, :edit, :update]

  get 'wishlist', to: 'services#wishlist', as: 'wishlist'
end

# create route
# create action for route wishlist in services controller
# load all users favorites into the instance variable
# create a view for the wishlist
# render list partial
# add link to navbar

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :price, presence: true
  validates :title, presence: true
  validates :description, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:title, :description, :price],
    associated_against: {
      user: [:name, :location]
  },
    using: {
      tsearch: { prefix: true }
  }
  scope :filter_by_price, lambda { |min_price, max_price|
    where(price: min_price..max_price)
  }

  has_many_attached :photos
  acts_as_favoritable
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_after_action :verify_authorized, only: :wishlist
  def index
    @user = current_user
    @services = policy_scope(Service)
    if params[:query].present?
      @services = Service.global_search(params[:query])
    else
      @services = Service.all
    end

    if params[:min_price].present? && params[:max_price].present?
      @services = @services.filter_by_price(params[:min_price].to_i, params[:max_price].to_i)
    end

    if @services.empty?
      flash.now[:notice] = "0 results"
    end
  end

  # def show
  #   @service = Service.find(params[:id])
  #   @reviews = @service.reviews
  #   @review = Review.new
  #   @booking = Booking.new
  #   authorize @service
  #   @marker = [{
  #     lat: @service.user.geocode[0],
  #     lng: @service.user.geocode[1]
  #   }]
  # end

  def show
    @service = Service.find(params[:id])
    @reviews = @service.reviews
    @review = Review.new
    @booking = Booking.new
    authorize @service

    @marker = []

    if @service.user&.geocode.present?
    @marker << {
      lat: @service.user.geocode[0],
      lng: @service.user.geocode[1]
    }
    end
  end


  def new
    @service = Service.new
    authorize @service
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    authorize @service
    if @service.save
      redirect_to service_path(@service)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @service = Service.find(params[:id])
    authorize @service
    @service.destroy
    redirect_to services_path
  end

  def toggle_favorite
    @service = Service.find_by(id: params[:id])
    authorize @service
    @user = current_user
    @user.favorited?(@service) ? @user.unfavorite(@service) : @user.favorite(@service)
    redirect_to services_path
  end

  def wishlist
    @service = Service.find_by(id: params[:id])
    @services = current_user.favorited_services
    @user = current_user
    render :wishlist
  end

private

  def service_params
    params.require(:service).permit(:price, :description, :title, :user_id, photos: [])
  end
end

app/views/services/_list.html.erb
<div class="cards-services" id="cards-services">
  <% @services.each do |service| %>
    <div class="card-service">
      <div class="service-photo position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= service.photos.attached? ? cl_image_path(service.photos.first.key) : "https://i1.sndcdn.com/avatars-UaKAHbGfoeypwb8c-qkYTMg-t240x240.jpg"%>)">
        <%= link_to toggle_favorite_service_path(service), class: "position-absolute top-0" do %>
          <% if user_signed_in? %>
            <i class="<%= @user.favorited?(service) ? "fa-solid fa-heart" : "fa-regular fa-heart" %>fa-lg custom-icon" ></i>
          <% end %>
        <% end %>
      </div>
      <%= link_to service_path(service), class:'text-decoration-none' do%>
        <div class="card-info">
          <div class="header">
            <h4><%= service.user.name %>,  <%= service.user.age %></h4>
          </div>
          <p class="text-muted"><%= service.title %></p>
          <div class="location">
            <i class="fa-solid fa-location-dot" style="color: #511f37;"></i>
            <p class="text-muted"><%= service.user.location %></p>
          </div>
          <div class="price">
            <i class="fa-solid fa-dollar-sign" style="color: #511f37;"></i>
            <p><%= service.price %>  per day</p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/services/_share.html.erb
<div class="container-services mt-5 pt-3"  id="services">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with(url: services_path, method: :get, class: "d-flex") do |form|%>
        <%= form.text_field :query, placeholder: "Type a keyword", class: "form-control"%>
        <%= form.number_field :min_price, placeholder: "Min Price", class: "form-control" %>
        <%= form.number_field :max_price, placeholder: "Max Price", class: "form-control" %>
        <%= form.submit "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div>
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
    </div>
  </div>
</div>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
    </div>
  </div>
</div>
<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="sr-only">Previous</span>
</a>
<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="sr-only">Next</span>
</a>

app/views/services/index.html.erb
<div><%= render "services/share" %></div>
<div><%= render "services/list" %></div>

app/views/services/new.html.erb
<div class="service-new">
  <div class="container-form">
    <h1>New offer from you!?</h1>
    <h2>Submit this form right now!!</h2>
    <%= simple_form_for(@service) do |f| %>
      <%= f.input :title %>
      <%= f.input :price %>
      <%= f.input :description %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit "Offer!", class:"btn btn-primary" %>
    <% end %>
    <br>
  </div>
</div>

app/views/services/show.html.erb
<div class="service-show-container">
  <div class="service-title">
    <h1><%= @service.title %></h1>
  </div>
  <div class="service-container">
    <div class="left">
      <div class="map-profile">
        <ul class="profile-cards">
          <% if @service.photos.attached?%>
            <% @service.photos.each do |photo| %>
              <li class="service-show-photo"><%= cl_image_tag(photo.key) %></li>
            <% end %>
          <% else %>
            <li class="service-show-photo"><img src="https://i1.sndcdn.com/avatars-UaKAHbGfoeypwb8c-qkYTMg-t240x240.jpg" alt=""></li>
          <% end %>
        </ul>
      </div>
      <div class="detail">
        <div class="name">
          <h2><%= @service.user.name %></h2>
        </div>
        <div class="age-gender">
          <div class="small-card">
            <p>Age <%= @service.user.age %></p>
          </div>
          <div class="small-card">
            <p><%= @service.user.sex.capitalize %></p>
          </div>
        </div>
        <div class="map-description">
          <div class="profile-description">
            <div class="profile-icon">
              <i class="fa-solid fa-earth-americas"></i>
            </div>
            <div class="profile-detail">
              <strong>Interest</strong>
              <p class="text-muted"><%= @service.user.interest%></p>
            </div>
            <div class="profile-icon">
              <i class="fa-solid fa-hippo"></i>
            </div>
            <div class="profile-detail">
              <strong>Description</strong>
              <p class="text-muted"> <%= @service.user.description %></p>
            </div>
            <div class="profile-icon">
              <i class="fa-solid fa-ban"></i>
            </div>
            <div class="profile-detail">
              <strong>Cancelation fee $25</strong>
            </div>
          </div>
        </div>
      </div>
      <div class="container-review" data-controller="review" >
        <div class="reviews" data-review-target='items'>
          <h1> <%= @reviews.length %> Reviews </h1>
          <% @reviews.each do |review| %>
            <%= render "reviews/review", review: review %>
          <% end %>
        </div>
        <%= render "reviews/form", service: @service, review: Review.new %>
      </div>
    </div>
    <div class="right">
      <div class="map-show">
        <div  style="width: 30vw; height: 40vh;"
        data-controller="map"
        data-map-markers-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        <p>Location: <%= @service.user.location %></p>
      </div>
      <div class="to-booking">
        <%# put condition for delete button %>
        <% if current_user == @service.user %>
          <div class="booking-card">
            <h3>You are the owner of this offer.</h3>
            <p>If you want to check someone booked you, please go to bookings page!</p>
            <%= link_to "Go to bookings", bookings_path, class:"btn btn-primary" %>
            <p></p>
            <%= link_to service_path(@service), data: {turbo_method: :delete, turbo_confirm: "Delete this offer? Are you sure? 😢"} do %>
              <i class="fa-solid fa-trash-can" style="color: #00cecb;"></i>
            <% end %>
          </div>
        <% else %>
          <div class="booking-card" data-controller="price">
            <div class="price-booking">
              <h5>$<span data-price-target="price"><%= @service.price %></span></h5>
              <p>&emsp;per day</p>
            </div>
            <%= simple_form_for [@service, @booking], data: { controller: 'flatpickr' } do |f| %>
              <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime", action: "change->price#calculate", price_target: "startTime" }  }  %>
              <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime", price_target: "endTime" }, id: 'end_time' } %>
              <%= f.submit "Book!",class:"btn btn-flat" %>
            <% end %>
            <div class="price-detail">
              <p class="text-muted">Price: $<span data-price-target="total"><%= @service.price %></span></p>
              <p class="text-muted">Tax: $30</p>
            </div>
            <div class="final-price">
              <b>Total with taxes $<span data-price-target="lasttotal"><%= @service.price + 30%></span></b>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/services/wishlist.html.erb
<div class= "d-flex flex-column align-items-center mt-5 pt-5">
  <h2>Your Wishlists</h2>
  <% if @services.empty? %>
    <p>Your wishlist is empty.</p>
  <% else %>
    <%= render "services/list" %>
  <% end %>
</div>