config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#home"

  resources :services, only: [:index, :show, :new, :create, :destroy] do
    member do
      get 'toggle_favorite', to: "services#toggle_favorite"
    end
    resources :bookings, except: [:destroy, :index, :edit, :update]
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]
  resources :bookings, only: [:destroy, :index, :edit, :update]

  get 'wishlist', to: 'services#wishlist', as: 'wishlist'
end

# create route
# create action for route wishlist in services controller
# load all users favorites into the instance variable
# create a view for the wishlist
# render list partial
# add link to navbar

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @service = Service.find(params[:service_id])
    @review = Review.new(review_params)
    @review.service = @service
    @review.user = current_user
    authorize @review
    respond_to do |format|
      if @review.save
        format.html { redirect_to service_path(@service) }
        format.json
      else
        @reviews = @service.reviews
        @booking = Booking.new
        @current_user_bookings = policy_scope(Booking.where(user: current_user))
        @none_rejected_bookings = current_user.bookings_as_owner.pending
        @other_bookings = current_user.bookings_as_owner do |booking|
          booking.status != "pending"
        end
        @pending_bookings = current_user.bookings.pending
        format.html { render "bookings/index", status: :unprocessable_entity }
        format.json
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to service_path(@review), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :user_id, :service_id)
  end
end

app/views/reviews/_form.html.erb
<%= simple_form_for(
  [service, review],
  data: {review_target: "form", action: "submit->review#send"}) do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment %>
    <%= f.submit class: "btn btn-flat"%>
<% end %>

app/views/reviews/_review.html.erb
<br>
<h3> <%= review.user.name  %> </h3>
<div class="d-flex justify-content-between">
  <p> 5/<%=review.rating%> <%= '❤️' * review.rating %> </p>
  <%= link_to review_path(review),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
    <i class="fa-solid fa-trash" style="color: #1D5D9B;"></i>
  <% end %>
</div>
<p> <%= review.comment  %> </p>
<br>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>