config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#home"

  resources :services, only: [:index, :show, :new, :create, :destroy] do
    member do
      get 'toggle_favorite', to: "services#toggle_favorite"
    end
    resources :bookings, except: [:destroy, :index, :edit, :update]
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]
  resources :bookings, only: [:destroy, :index, :edit, :update]

  get 'wishlist', to: 'services#wishlist', as: 'wishlist'
end

# create route
# create action for route wishlist in services controller
# load all users favorites into the instance variable
# create a view for the wishlist
# render list partial
# add link to navbar

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('banner-img.jpg') %>);">
  <div class="container">
    <h1><strong>Hive</strong> </h1>
    <p>Connect with exceptional individuals who can transform your life. <br>
      Find your perfect match and start meaningful connections
      .</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hive</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%#= favicon_link_tag asset_path('icon.png') %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  </head>

  <body>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to services_path, class: "navbar-brand" do %>
      <i class="fas fa-balloons"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</div>

    <% if user_signed_in? %>
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <div class="container-fluid">
          <%= link_to services_path, class: "navbar-brand" do %>
            <i class="fas fa-balloons"></i>
          <% end %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <%= link_to "Home", root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Messages", "#", class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
              <%= image_tag current_user.photo.attached? ? cl_image_tag(current_user.photo.key) : 'default_avatar.jpeg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Be a partner 👫", new_service_path, class: "dropdown-item" %>
                  <%= link_to 'Wishlists', wishlist_path, class: "dropdown-item"%>
                  <%= link_to "Bookings ❤️", bookings_path, class: "dropdown-item" %>
                  <%= link_to "Log out", "/users/sign_out", class: "dropdown-item", data: {turbo_method: :delete} %>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <%= yield %>
    <div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">

    </ul>
    <p class="text-center text-muted">© 2023 Hive</p>
  </footer>
</div>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </body>
</html>